### ISSUE TITLE
question here , not an issue

### ISSUE THREAD

**Issue by velteyn** [oboshape-godot/3-HoppyDays-GD-Using-Version-3.2#1]
Hello and great job !!
I'm a Godot student also and I have a problem on MY code..
I'm on lesson 40 is_on_ceiling() from udemy but I cannot make it work...
It seams that is_on_ceiling() is never hit while is_on_floor works correctly.
I noticed you put 3 collision shape I have only one as the teacher said.. Is that a workaroud.

Im stuck in to this issue thankyou

**Comment by OboShape** [comment]
Hi @velteyn ,  sorry i should have taken that out or created a new fork for it.
I was testing if compound colliders would work for someone elses bug they were having and i uploaded to test on another computer.

ive reverted it to a single collision shape, the way it should be.

**Comment by OboShape** [comment]
if you have your project up on github, or somewhere else, i dont mind having a look for you if you want. to see if its anything i can spot

**Comment by velteyn** [comment]
sure !!
I have it here https://mega.nz/file/Fdc0DIpS#6QM0miJ3bx0aE5I7qRWTNaVjb9-S8cdFo8R-eNt_bBg

**Comment by velteyn** [comment]
Ah thank you !! My bad !! It was a simple "priority check" issue... I should had found myself !!! 
Again thank you so much

**Comment by OboShape** [comment]
no probs, glad its working and taking shape ;)
